# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'weibo-OC' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'YYModel'
pod 'pop'
pod 'YYText'
pod 'FMDB'
  # Pods for weibo-OC

  target 'weibo-OCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weibo-OCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
